HLT_triggers_prescales:
  2022_preEE:
    BTagMu:
      HLT_BTagMu_AK4Jet300_Mu5: 0.971
      HLT_BTagMu_AK8DiJet170_Mu5: 5.046
      HLT_BTagMu_AK8Jet170_DoubleMu5: 0.971
      HLT_BTagMu_AK8Jet300_Mu5: 1.208
  2023_preBPix:
    BTagMu:
      HLT_BTagMu_AK4Jet300_Mu5: 0.999
      HLT_BTagMu_AK8DiJet170_Mu5: 11.994
      HLT_BTagMu_AK8Jet170_DoubleMu5: 0.999
      HLT_BTagMu_AK8Jet300_Mu5: 1.999
