ptetatau21_reweighting:
  2022_preEE: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_preEE_reweighting.json
  2022_postEE: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2022_postEE_reweighting.json
  2023_preBPix: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_preBPix_reweighting.json
  2023_postBPix: ${config_dir:}/ptetatau21_reweighting/FatJetGood_pt_eta_tau21_2023_postBPix_reweighting.json
