HLT_triggers:
    2022_preEE:
        BTagMu:
        - BTagMu_AK8DiJet170_Mu5
        - BTagMu_AK8Jet170_DoubleMu5
        - BTagMu_AK8Jet300_Mu5
        - BTagMu_AK4Jet300_Mu5
    2022_postEE:
        BTagMu:
        - BTagMu_AK8DiJet170_Mu5
        - BTagMu_AK8Jet170_DoubleMu5
        - BTagMu_AK8Jet300_Mu5
        - BTagMu_AK4Jet300_Mu5
    2023_preBPix:
        BTagMu:
        - BTagMu_AK8DiJet170_Mu5
        - BTagMu_AK8Jet170_DoubleMu5
        - BTagMu_AK8Jet300_Mu5
        - BTagMu_AK4Jet300_Mu5
    2023_postBPix:
        BTagMu:
        - BTagMu_AK8DiJet170_Mu5
        - BTagMu_AK8Jet170_DoubleMu5
        - BTagMu_AK8Jet300_Mu5
        - BTagMu_AK4Jet300_Mu5
